services:

  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    build: .
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=pyspark==3.5.0
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      - PYTHONPATH=/opt/airflow/
    volumes:
      - ../pipeline/dags:/opt/airflow/dags 
      - ../pipeline:/opt/airflow/pipeline
      - ../data:/opt/airflow/data
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Hugo --lastname Souza --role Admin --email admin@email.com
      "

  airflow-webserver:
    build: .
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=pyspark==3.5.0
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      - PYTHONPATH=/opt/airflow
    volumes:
      - ../pipeline/dags:/opt/airflow/dags 
      - ../pipeline:/opt/airflow/pipeline
      - ../data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=pyspark==3.5.0
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_super_secret_key_123
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__REMOTE_LOGGING=False
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      - PYTHONPATH=/opt/airflow
    volumes:
      - ../pipeline/dags:/opt/airflow/dags
      - ../pipeline:/opt/airflow/pipeline
      - ../data:/opt/airflow/data
    command: scheduler